### ISSUE TITLE
Is it abandoned

### ISSUE THREAD

**Issue by ugintl** [web2project/web2project#341]
If you are not interested in this project anymore, please transfer ownership to someone else. There are some pull requests worth your attention. Thanks.

**Comment by opto** [comment]
thanks for the info. I haven't received any notification by github and will have a look.

**Comment by ugintl** [comment]
@opto Thanks. And there are some issues as well.

**Comment by caseysoftware** [comment]
I'm wrapping a number of other things and hope to clean up a few things here and bring it more up to date soon. I'll dig into the PRs and Issues.. I haven't been getting notifications on any of them.

**Comment by derStephan** [comment]
@ugintl You can try the equally abandoned [dotProject](https://github.com/dotproject/dotProject).

Funny thing is that web2Project started because dotProject development stalled at the time. I assume that there is too little need for a self-hosted PHP project management tool to keep up the effort. 

Everything today has to be run by strangers in the cloud for just a little monthly fee per user. I really do not understand, why anyone would walk down that road in the first place but here we are. 

Thanks to @caseysoftware and @ajdonnison for the long years of tedious work. If you re-joined forces there might be enough shoulders to carry the future development. Until then, I am afraid that both projects are dead.

**Comment by caseysoftware** [comment]
I don't particularly like that conclusion but I'd say it's accurate. Unfortunately, there hasn't been much interest in web2project for 5+ (or more) years and it takes a backseat to life.

If @opto expressed interest, I'd look into handing it over.

**Comment by derStephan** [comment]
>I don't particularly like that conclusion but I'd say it's accurate.

Sorry. I did not mean to offend you. We still use web2Project and I am grateful for it.

**Comment by caseysoftware** [comment]
Zero offense taken

**Comment by caseysoftware** [comment]
I'm working on PHP 8 compatibility and updating some of the underlying libraries now.
So far ADODB and PEAR/Date were the biggest problems, still tracking through others.

**Comment by ugintl** [comment]
@caseysoftware thank you for your contribution. Generally speaking, when updating a PHP app from 7 to 8, how do you know which parts to update? Is there a software or technique that highlights the areas that need to be updated? Or it is pure experience?

**Comment by caseysoftware** [comment]
Two main methods:
- Working through the migration guide - https://www.php.net/manual/en/migration80.php
- Watching for Fatal errors in the PHP error log as I click around

**Comment by caseysoftware** [comment]
Btw, here's the current progress on the PHP8 compatibility work:
https://github.com/web2project/web2project/tree/php-8-compat

There are a ton of other supporting changes to bring everything more up to date which included some database changes, a bunch of better error handling and the like.

Two major open items:
- The System module doesn't work properly. It has a database error when it checks for new versions.
- The Tasks module doesn't display tasks (oops!) as the query has a non-aggregated field in an otherwise aggregated query.

I suspect Gantt charts aren't going to work right now either as the version of jpGraph is ancient.

**Comment by caseysoftware** [comment]
And just cleaned up the Tasks module and updated jpgraph:

- Tasks are displaying
- Gantt charts are now working

I'm still working through two things:
- There are some projects that won't generate a Gantt chart. Not sure if it's a system issue or something with my projects.
- The `system` module is still broken as noted above.

**Comment by jan-b** [comment]
Hi Keith
May I ask witch vendor are supposed to be installed with web2project 4.0?
PHP Warning:  require(/var/www/html/web2project/vendor/composer/platform_check.php
.This page isn’t working
